{{- $intialKey := splitList "=KEY:" .Values.genesis.signatureProvider | first -}}
{{- $myDict := dict "initial_timestamp" .Values.genesis.initial_timestamp  "initial_key" $intialKey "initial_configuration" .Values.genesis.initial_configuration -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eosio-testnet.fullname" . }}
  labels:
    app: {{ include "eosio-testnet.name" . }}
    chart: {{ include "eosio-testnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  genesis.json: |-
    {{ toJson $myDict }}
  boot-nodeos.sh: |-
{{ .Files.Get "eosio/boot-nodeos.sh" | indent 4 }}
  logging.json: |-
{{ .Files.Get "eosio/logging.json" | indent 4 }}
  nodeos_wrapper.sh: |-
{{ .Files.Get "eosio/nodeos_wrapper.sh" | indent 4 }}
{{- if .Values.producer_keys }}
  producer_keys.txt: |-
    {{- range .Values.producer_keys }}
    Private key: {{ index . "private" }}
    Public key: {{ index . "public" }}
    {{- end }}
{{- end }}