apiVersion: v1
kind: Service
metadata:
  name: {{ include "eosio-testnet.biosfullname" . }}
  labels:
    app: {{ include "eosio-testnet.name" . }}
    chart: {{ include "eosio-testnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: peer-to-peer
  selector:
    app: bios
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eosio-testnet.nodeosfullname" . }}
  labels:
    app: {{ include "eosio-testnet.name" . }}
    chart: {{ include "eosio-testnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
      protocol: TCP
  selector:
    app: nodeos
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eosio-testnet.headlessService" . }}
  labels:
    app: {{ include "eosio-testnet.name" . }}
    chart: {{ include "eosio-testnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: peer-to-peer
  selector:
    app: nodeos
    release: {{ .Release.Name }}